
stages:
  - build
  - dockerize
#  - deploy

variables:
  HARBOR_REPO: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/easyoa-server
  DOCKER_IMAGE_TAG: "4.0.3"
  HARBOR_USERNAME: $HARBOR_USERNAME
  HARBOR_PASSWORD: $HARBOR_PASSWORD
  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/docs/settings.xml"
  DOCKERFILE_PATH: "."
  HARBOR_IMAGE: ${HARBOR_REPO}/easyoaserver
  MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
  MINIO_SECRET: $MINIO_SECRET
  EMAIL_PASSWORD: $EMAIL_PASSWORD
  MYSQL_PASSWORD: $MYSQL_PASSWORD

cache:
  paths:
    - helper-custom-server/target/helper-custom-server-1.0-SNAPSHOT.jar

build:
  stage: build
  image: maven:3.6.3-openjdk-17 # 使用 Maven 3.6.3 和 Java 17 的官方镜像
  tags:
    - aifile-docekr
  script:
      - mvn ${MAVEN_CLI_OPTS} clean package
  artifacts:
    paths:
      - ./helper-custom-server/target/helper-custom-server-1.0-SNAPSHOT.jar

dockerize:
  stage: dockerize
  image: docker:24.0.5
  tags:
    - aifile-docekr
  script:
    - docker build -t easy-oa-server:$DOCKER_IMAGE_TAG --build-arg minioaccessKey=$MINIO_ACCESS_KEY --build-arg miniosecretKey=$MINIO_SECRET --build-arg emailpassword=$EMAIL_PASSWORD --build-arg mysqlpassword=$MYSQL_PASSWORD $DOCKERFILE_PATH
    - docker login -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD" $HARBOR_REPO
    - docker tag easy-oa-server:$DOCKER_IMAGE_TAG $HARBOR_IMAGE:$DOCKER_IMAGE_TAG
    - docker tag easy-oa-server:$DOCKER_IMAGE_TAG $HARBOR_IMAGE:latest
    - docker push $HARBOR_IMAGE:$DOCKER_IMAGE_TAG
    - docker push $HARBOR_IMAGE:latest

#deploy:
#  stage: deploy
#  tags:
#    - aifile-docekr
#  script:
#
#    - eval $(ssh-agent -s) # 启动 ssh-agent
#    - ssh-add ~/.ssh/id_rsa
#    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_REPO"
#    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull $HARBOR_IMAGE:$DOCKER_IMAGE_TAG"
#    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker stop easyoa-server || true && docker rm easyoa-server || true"
#    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker run -d --name easyoa-server $HARBOR_IMAGE:$DOCKER_IMAGE_TAG"
#  only:
#    - master