version: '3.3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1
    ports:
      - "18080:8080"
    environment:
      PARAMS: '
        --spring.datasource.url=jdbc:mysql://192.168.12.12:13306/xxl_job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        --spring.datasource.username=root
        --spring.datasource.password=aizhineng1404
        --xxl.job.accessToken=xxl-job-aizhineng1404'

    volumes:
      - ./logs:/data/applogs

    restart: always

