server:
  port: 55550
  servlet:
    # Controller统一前缀
    context-path: /api
spring:
  application:
    name: printes
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.12.12:3306/print?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 13
    port: 6379
    password:
    jedis:
      pool:
        max-active: 40
        max-wait: -1
        max-idle: 50
        min-idle: 25
    timeout: 6000
    host: 192.168.12.12
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    #上边这个开启sql日志
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: false
  global-config:
    #雪花算法
    db-config:
      id-type: ASSIGN_ID

# ====================== ↓↓↓↓↓↓ MinIO文件服务器 ↓↓↓↓↓↓ ======================
minio:
  url: http://10.15.247.254:9090
  accessKey: N2T6ZfARSupeUYbn
  secretKey: nqcG5pG9Qc104lHrWgVZCYrc2JZSyS0v
  bucketName: aistudio

# ====================== ↓↓↓↓↓↓ CAS认证相关配置 ↓↓↓↓↓↓ #############################################
cas:
  baseUrl: http://10.15.247.254:55555/
  clientId: 93519f52770144c7afa01c1f76409d81
  clientSecret: 0a28768c96db4ab79eec56b70fade03c
study:
  minOldTime: 420 #单位：分钟
  # 就是10点前的意思
  maxFirstTime: 10